# -*- coding: utf-8 -*-
"""qES.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ToPx6iz7RmaNCjvaZcWGxi60qx3OWzUb
"""

import numpy as np

def ES(losses, confidence=None, VaR=None):
    if VaR is None:
        VaR = np.percentile(losses, 100 * confidence)

    # Calculate ES as the average of losses exceeding the VaR threshold
    es_value = np.mean(losses[losses > VaR])
    return es_value


# Unit test
u = np.random.uniform(0, 100, 100000)

# Test the ES function with a confidence of 0.8
es_confidence = ES(losses=u, confidence=0.8)
print('ES with confidence:', np.round(es_confidence, 0) == 90)

# Test the ES function with a VaR of 80
es_var = ES(losses=u, VaR=80)
print('ES with VaR:', np.round(es_var, 0) == 90)